[env:ch32v003f4p6]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = ch32v003f4p6_evt_r0
framework = ch32v003fun
monitor_speed = 115200
upload_protocol = minichlink
build_flags = -DIR_DEBUG_LOG=0
build_src_filter = +<*> -<tetris.c>

